"""added columns content_type, size

Revision ID: e4a10f4f7dd6
Revises: 06c8602b33e0
Create Date: 2026-05-23 02:49:57.589015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a10f4f7dd6'
down_revision: Union[str, Sequence[str], None] = '06c8602b33e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'size')
    op.drop_column('file', 'content_type')
    # ### end Alembic commands ###
