services:
  db:
    image: pgvector/pgvector:pg17 # pulling the prebuilt image
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile # building custom image from Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      CLIENT_URL: http://localhost:5173
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pg_db
    volumes:
      - ./api/app:/app/app
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile # building custom image from Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    volumes:
      - ./web/src:/app/src
    depends_on:
      - api
  
volumes:
  pgdata: